### PR TITLE
turned IntoVerticesSource into Into<VerticesSource> Issue #741

### PR DESCRIPTION
**Pull request by Roxxik**
fixing Issue #741 , there are just some IntoIterator's and IntoIter's left

### CODE REVIEW

**Comment by tomaka** [comment]
Thanks!

This is a breaking change though, so I'll merge it before 0.14.

**Comment by Roxxik** [comment]
No problem ;) i'm just getting into OSS, git and rust and am just picking some low-hanging fruits/fixes

**Comment by daboross** [comment]
Would it make sense to merge this for 0.20.0? It seems like a good change and there is already a breaking change in the repository right now.

I've rebased the changes onto master and fixed the one new merge conflict in https://github.com/daboross/glium/tree/i741 - I don't know if it would be better to PR this to roxxik/glium:i741 or make a new PR to glium/glium though.

**Comment by tomaka** [comment]
Yeah a new PR would be better

**Comment by daboross** [comment]
Alright- opened #1661.

**Pull request closed without merging**
