### PR TITLE
Replace all instances of mem::uninitialized in comments with assume_init

### PR DESCRIPTION
**Pull request by LiamTheProgrammer**
Since mem::uninitialized is a deprecated part of std, I figured that through some search and replace the comments could be improved. The instances of mem::uninitialized got replaced with MaybeUninit and assume_init, which is still unsafe, but at least it's not deprecated. I ran all tests on my computer and built glium successfully.

### CODE REVIEW

**Comment by LiamTheProgrammer** [comment]
I think this might solve https://github.com/glium/glium/issues/1767

**Comment by est31** [comment]
Doing assume_init without initializing is as ub as using uninitialized. I'm not really sure the new solution is better. Could you instead put the example code into functions like:

```
#fn foo(display: glium::Display) {
display.do_something();
#}
```

**Comment by est31** [comment]
Also, could you please delete the todo.txt file? thanks!

**Comment by LiamTheProgrammer** [comment]
At least it isn't deprecated. But yeah, I'll remove todo.txt. Since the uninitialized memory is handled in the right way here once it's made IIRC, I don't think it's a danger to have it this way.

**Comment by est31** [comment]
Thanks for removing the todo file. Could you also remove the assume_init in favour of the function based approach I described?

**Comment by LiamTheProgrammer** [comment]
@est31 Ok.

**Comment by LiamTheProgrammer** [comment]
@est31 I'll look back at this tomorrow.

**Comment by est31** [comment]
@LiamTheProgrammer deal!

**Pull request merged**
