### PR TITLE
Re-export winit

### LINKED ISSUE #2086: Re-export winit
There are a lot of public exposed APIs that accept and return winit types (ie):

https://github.com/glium/glium/blob/1676f0de6dddfa294f834613372f5096a429acd8/src/backend/glutin/mod.rs#L333

Also, most of the tutorials make heavy use of the winit APIs.

Currently this requires users to figure out which version of winit is currently being used, and make sure their winit dependency stays in sync with the glium dependency, otherwise it will be a breaking change if your API expects a 0.29 EventLoop when the user is still using a 0.28 EventLoop.

It seems like you are aware of this, and are bumping semver minor to signify pre-1.0.0 breaking changes whenever you bump the winit dependency to a breaking change.

Since that is already a requirement on your library, you might as well re-export winit explicitly and change the tutorials to recommend using the re-export.

### PR DESCRIPTION
**Pull request by junderw**
Closes #2086 

I ran all the checks in the CI yaml, but actually running clippy and `cargo test` (actually running the tests) gave me tons of errors in places I didn't touch.

### CODE REVIEW

**Comment by junderw** [comment]
beta and nightly failures are unrelated...

I wonder what caused them...

**Comment by est31** [comment]
> I wonder what caused them...

I have fixed the warnings in #2116.

**Comment by junderw** [comment]
Rebased on master

**Review by est31 — APPROVED** [review]

**Comment by est31** [comment]
Thanks for taking the time to make a PR!

**Pull request merged**
