### PR TITLE
Restructure book files for mdbook

### PR DESCRIPTION
**Pull request by NifleySnifley**
- Moved markdown files for the book to `book/src/`
- Moved image files for the book to `book/src/resources/`
- Moved `book/README.md` to `book/src/` and used it as the introduction for the mdbook
- Added configuration files and `.gitignore` for mdbook

### CODE REVIEW

**Comment by est31** [comment]
I don't like deep levels of directories. Can we keep it mdbook compatible but keep the files in the `book/` directory, not moving them to `book/src/`? Otherwise the PR seems good. Sorry for the late review.

**Comment by NifleySnifley** [comment]
Thanks for the feedback, I moved the markdown files and resources directory from `book/src` to `book/` and fixed capitalization in the title. If there's anything else, let me know!

**Review by est31 — APPROVED** [review]
Thanks!

**Comment by est31** [comment]
Now what's missing is automatted CI pushing the book to a website or something like that. I'll look into it.

**Comment by NifleySnifley** [comment]
Awesome, it would be really cool to have it deployed on Github pages or something.

**Comment by est31** [comment]
Right now you have to generate it yourself. Ideally it'd be deployed to github pages, I've created #1988 as an issue for tracking it.

**Comment by est31** [comment]
@Peter-Crawley it can now be viewed on https://glium.github.io/glium/book/ .

**Comment by Peter-Crawley** [comment]
Cool, thanks!

**Pull request merged**
