### PR TITLE
Added Dynamic Uniform based on HashMap.

### PR DESCRIPTION
**Pull request by DoeringChristian**
Sometimes I find it useful to add uniforms in various parts of my program therefore I propose a Uniforms struct that stores the Values in a HashMap Where one can add them dynamically.

I'm not quite sure if this is needed or if there is a better way to do it but here is my implementation.

Feedback is welcome.

### CODE REVIEW

**Review by est31 — APPROVED** [review]
Thanks!

**Comment by Melchizedek6809** [comment]
Can this PR be merged? Sounds convenient to have.

**Comment by est31** [comment]
Right now github is saying there is a merge conflict, but otherwise yes it can be merged.

**Comment by Melchizedek6809** [comment]
Sweet, I'll take a look at the conflict, maybe it's easy to resolve.

**Comment by DoeringChristian** [comment]
Sorry, made a mistake that I did not catch compiling the project.
I think this should resolve the merge conflict. However, someone should still look over it so that I did not make a mistake.

**Comment by est31** [comment]
@DoeringChristian thanks, can you squash? Alternatively, we squash during merging of the PR. This keeps a clean history.

**Comment by DoeringChristian** [comment]
> @DoeringChristian thanks, can you squash? Alternatively, we squash during merging of the PR. This keeps a clean history.

Unfortunately I'm not quite familiar on how to do that.

**Comment by est31** [comment]
Don't worry then! We'll do that instead, there is a button on github for it.

**Comment by DoeringChristian** [comment]
Thanks.

**Comment by Melchizedek6809** [comment]
Thank you for your contribution! Say, would you be interested in writing a small example to showcase these dynamic uniforms? Might be a nice way for people to know that this is possible.

**Comment by DoeringChristian** [comment]
I can't quite think of an easy example. If I remember correctly I implemented this so that you would be able set uniforms from trait objects for polymorphism. Here I adapted the basic triangle example but with DynamicUniforms:
```rust
use glium::uniforms::DynamicUniforms;

#[macro_use]
extern crate glium;

struct Triangle {
    x: f32,
}

impl Triangle {
    pub fn upload<'a>(&'a self, uniforms: &mut DynamicUniforms<'a, 'a>) {
        uniforms.add("t", &self.x);
    }
}

fn main() {
    #[allow(unused_imports)]
    use glium::{glutin, Surface};

    let event_loop = glutin::event_loop::EventLoop::new();
    let wb = glutin::window::WindowBuilder::new();
    let cb = glutin::ContextBuilder::new();
    let display = glium::Display::new(wb, cb, &event_loop).unwrap();

    let mut triangle = Triangle { x: 0. };

    #[derive(Copy, Clone)]
    struct Vertex {
        position: [f32; 2],
    }

    implement_vertex!(Vertex, position);

    let vertex1 = Vertex {
        position: [-0.5, -0.5],
    };
    let vertex2 = Vertex {
        position: [0.0, 0.5],
    };
    let vertex3 = Vertex {
        position: [0.5, -0.25],
    };
    let shape = vec![vertex1, vertex2, vertex3];

    let vertex_buffer = glium::VertexBuffer::new(&display, &shape).unwrap();
    let indices = glium::index::NoIndices(glium::index::PrimitiveType::TrianglesList);

    let vertex_shader_src = r#"
        #version 140
        in vec2 position;
        uniform float t;
        void main() {
            vec2 pos = position;
            pos.x += t;
            gl_Position = vec4(pos, 0.0, 1.0);
        }
    "#;

    let fragment_shader_src = r#"
        #version 140
        out vec4 color;
        void main() {
            color = vec4(1.0, 0.0, 0.0, 1.0);
        }
    "#;

    let program =
        glium::Program::from_source(&display, vertex_shader_src, fragment_shader_src, None)
            .unwrap();

    let mut t: f32 = -0.5;
    event_loop.run(move |event, _, control_flow| {
        match event {
            glutin::event::Event::WindowEvent { event, .. } => match event {
                glutin::event::WindowEvent::CloseRequested => {
                    *control_flow = glutin::event_loop::ControlFlow::Exit;
                    return;
                }
                _ => return,
            },
            glutin::event::Event::NewEvents(cause) => match cause {
                glutin::event::StartCause::ResumeTimeReached { .. } => (),
                glutin::event::StartCause::Init => (),
                _ => return,
            },
            _ => return,
        }

        let next_frame_time =
            std::time::Instant::now() + std::time::Duration::from_nanos(16_666_667);
        *control_flow = glutin::event_loop::ControlFlow::WaitUntil(next_frame_time);

        // we update `t`
        triangle.x += 0.0002;
        if t > 0.5 {
            t = -0.5;
        }

        let mut target = display.draw();
        target.clear_color(0.0, 0.0, 1.0, 1.0);
        let mut uniforms = DynamicUniforms::new();

        triangle.upload(&mut uniforms);

        target
            .draw(
                &vertex_buffer,
                &indices,
                &program,
                &uniforms,
                &Default::default(),
            )
            .unwrap();
        target.finish().unwrap();
    });
}
```
However, I forgot the exact use-case I had for this solution. So maybe someone else can think of a better example.

**Pull request merged**
