### PR TITLE
Update glutin to 0.30

### PR DESCRIPTION
**Pull request by est31**
https://github.com/rust-windowing/glutin/releases/tag/v0.30.0

### CODE REVIEW

**Comment by kchibisov** [comment]
@est31 if you need help with glutin update you can ping me on #winit IRC/matrix or here. In general I think you can remove winit entirely from the glutin integration? Like some functions like rebuilding the context could be done without a window for example, and you may only need `raw-window-handle` in some places.

If you still want `winit` for outside the examples you might want to look at [`glutin-winit`](https://github.com/rust-windowing/glutin/pull/1517). Though, I don't see a need for winit inside your code.

The window and context are also not related to each other since on Android you have your window live for a cycle of `Resume` and `Suspend` events, but `Context` lives as long as it wants.

Though given that you have a signature of `swap_buffers(&self)` it seems like you may want to either change the `Backend` trait or tie `GlSurface` and `GlContext` from new glutin together. And have a method to change surface associated with the context.

You can also consider using Traits glutin exposes, so you can have it automatically working not only for top-level stuff, but for `api::egl::Surface`, since they all implement the same traits, but it's not really an issue, users can always wrap their specialized stuff into `glutin::surface::Surface`.

**Comment by est31** [comment]
@kchibisov thanks for reaching out and offering help with the migration. I will join IRC to discuss it with you.

**Comment by est31** [comment]
@wez thanks for the feedback. I need to find time to get back to this PR, right now and at least the coming week I don't have much time for it. If you want, help is welcome :). My goal is to have glium use winit by default, but to make it optional.

**Comment by Melchizedek6809** [comment]
@est31 I've been working a bit starting from your branch and got a triangle to show, still super rough and dirty but might be helpful: https://github.com/Melchizedek6809/glium/tree/update_glutin
If you're still busy I can continue working on this, kinda fun to dive into the internals, just want to make sure that there's no wasted effort.

**Comment by est31** [comment]
@Melchizedek6809 that's very cool! I probably won't have time to dedicate on this soon-ish so it would be really great if you took over. It's great that you got a triangle to render :).

**Comment by Melchizedek6809** [comment]
@est31 Alright, then I'll continue and ask you once there's something sensible to review :)

**Comment by est31** [comment]
Closing in favour of #2036

**Pull request closed without merging**
