### PR TITLE
doc: 0.33 not available on crates, added workaround

### PR DESCRIPTION
**Pull request by DaraghD**
https://github.com/glium/glium/issues/2072
https://github.com/glium/glium/issues/2071

### CODE REVIEW

**Comment by est31** [comment]
Tbh I'd just do a release directly, rather than merging this. @Melchizedek6809 do you see anything we should do before a 0.33 release?

**Comment by Melchizedek6809** [comment]
@est31 Should be good to go, maybe a notice about the breaking API change in the readme to lessen the suprise, but apart from that things have worked quite reliably during testing.

**Comment by est31** [comment]
We should probably also get #2076 in before the release.

**Comment by fayalalebrun** [comment]
@est31 Is there anything else before the 0.33 release can be made?

**Comment by est31** [comment]
@fayalalebrun I've made the 0.33 release just now. Thanks to everyone who sent/reviewed PRs!

**Pull request closed without merging**
