### PR TITLE
Rename context → cb, window → wb

### PR DESCRIPTION
**Pull request by est31**
As suggested here: https://github.com/glium/glium/pull/1736#discussion_r275103767

r? @mitchmindtree @ZeGentzy

### CODE REVIEW

**Comment by ZeGentzy** [comment]
For consistency, let's change these too: 
https://github.com/est31/glium/blob/a4b8d9dfdce87b31a6baba5f1ed327829ab0cefb/examples/manual-creation.rs#L32
https://github.com/est31/glium/blob/a4b8d9dfdce87b31a6baba5f1ed327829ab0cefb/examples/gpgpu.rs#L9
https://github.com/est31/glium/blob/a4b8d9dfdce87b31a6baba5f1ed327829ab0cefb/src/backend/glutin/mod.rs#L65
https://github.com/est31/glium/blob/a4b8d9dfdce87b31a6baba5f1ed327829ab0cefb/src/backend/glutin/mod.rs#L129

**Comment by est31** [comment]
@ZeGentzy thanks for the review! I addressed the comment. Ready for merge now, @mitchmindtree.

**Comment by est31** [comment]
@mitchmindtree want to merge this too? Thank you!

**Comment by mitchmindtree** [comment]
Looks like this might need a rebase?

**Comment by est31** [comment]
Rebased!

**Pull request merged**
