### PR TITLE
Dropped glium-macros crate

### PR DESCRIPTION
**Pull request by Cerber-Ursi**
This is an intermediate change, more technical then meaningful.

This PR allows the glium_macros crate to compile on current stable Rust. It exports two derive macros, corresponding to the `Vertex` and `Uniform` traits in `glium`. The implementation for `Vertex` is exactly the same as in the previously available code; the implementation for `Uniform` was changed according to the change in the trait itself.

Note that the derived implementations are _not_ tested for correctness yet (and they will surely change, since at least one part of them currently seems to be unsound); the only test currently present is a "smoke" test, showing that the derive can be compiled. This will be changed with further PRs.

### CODE REVIEW

**Comment by est31** [comment]
Thanks, but note that this effort has already happened in the form of the `glium_derive` crate: https://github.com/glium/glium_derive . See also the discussion in #1791. Maybe focus your efforts there?

Ideally the macros crate would be removed from this repo. Feel free to update your PR to do this.

**Comment by Cerber-Ursi** [comment]
Thanks, I've missed it, will look through there.

**Comment by est31** [comment]
This is partially the fault of the project for not removing that crate for good.

**Comment by Cerber-Ursi** [comment]
Sorry for the delay. Updated.

**Pull request merged**
