### PR TITLE
Add repr(C) for Data struct in gpgpu-example

### PR DESCRIPTION
**Pull request by avl**
This struct should be repr(C), since nothing is guaranteed about the struct layout in rust without this directive. And we *are* actually relying on the struct layout ending up identically to the OpenGL std140-layout (which, with our explicit padding, it will if be guaranteed to if we specify repr(C)).

### CODE REVIEW

**Comment by est31** [comment]
Good point, thank you! Wish to rebase?

**Comment by avl** [comment]
I'll take a look at it shortly!

**Comment by avl** [comment]
See if this looks right now!

**Comment by est31** [comment]
Yes, it's been merged now. Thanks for your PR!

**Pull request merged**
